// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUoyI0bFN_uvNy-VpUDcrgxgLB4fZdfOA',
    appId: '1:631536859986:web:0e323795e76694ed1e988b',
    messagingSenderId: '631536859986',
    projectId: 'check-timer-58811',
    authDomain: 'check-timer-58811.firebaseapp.com',
    storageBucket: 'check-timer-58811.firebasestorage.app',
    measurementId: 'G-DWKXZYGMS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMc-m4BRGnvte16Ogjnxv3qS4mWozL_Aw',
    appId: '1:631536859986:android:b26e8cd2ee14a7fa1e988b',
    messagingSenderId: '631536859986',
    projectId: 'check-timer-58811',
    storageBucket: 'check-timer-58811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWcr6gx2286rt2HcBs8ZaHcBVzzeAb1vM',
    appId: '1:631536859986:ios:d83d534fb5bfd8d21e988b',
    messagingSenderId: '631536859986',
    projectId: 'check-timer-58811',
    storageBucket: 'check-timer-58811.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWcr6gx2286rt2HcBs8ZaHcBVzzeAb1vM',
    appId: '1:631536859986:ios:d83d534fb5bfd8d21e988b',
    messagingSenderId: '631536859986',
    projectId: 'check-timer-58811',
    storageBucket: 'check-timer-58811.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUoyI0bFN_uvNy-VpUDcrgxgLB4fZdfOA',
    appId: '1:631536859986:web:836dfa27c05713ff1e988b',
    messagingSenderId: '631536859986',
    projectId: 'check-timer-58811',
    authDomain: 'check-timer-58811.firebaseapp.com',
    storageBucket: 'check-timer-58811.firebasestorage.app',
    measurementId: 'G-3GQKD3Y3NL',
  );
}
